version: '3'
services:
  postgres-db:
    image: "postgres:12"
    container_name: "node-gmp-db"
    environment:
      - POSTGRES_USER=node_data
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node_data
    restart: always
    ports:
      - '5432:5432'
