GET http://localhost:3000/api/products
Accept: application/json
x-user-id: 0fe36d16-49bc-4aab-a316-f84df9

###
# Create a user
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "Test4 Test4 Alex",
  "email": "test4@example.com"
}

###
# Get all users
GET http://localhost:3000/api/users

###
# Delete user
DELETE http://localhost:3000/api/users/653228d7c76c0bbc274cc19c
x-user-id: 653228d7c76c0bbc274cc19c

#
# CARTS
#

###
# create cart
POST http://localhost:3000/api/profile/cart
x-user-id: a141d3e3-1dd4-4578-821e-61795d646534

{
  "user_id": "a141d3e3-1dd4-4578-821e-61795d646534"
}
