###
GET http://localhost:3000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQwZDQyNzZlMDljZDlhNjNhM2I1Y2YiLCJlbWFpbCI6InRlc3QxMjMzMjFAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5ODc0OTgxOCwiZXhwIjoxNjk4NzU3MDE4fQ.9jcLUnVRMJqpDZDDvyNTPhIt065T7wuR9UPJrU_Y63k


###
# Create a user
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "Alex",
  "lastName": "Test",
  "isAdmin": false,
  "email": "test123321@example.com",
  "password": "12341234"
}

###
# Create an Admin
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "Admin123",
  "lastName": "Test",
  "isAdmin": true,
  "email": "Admin1@example.com",
  "password": "1234admin"
}

###
# login user
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "test123321@example.com",
  "password": "12341234"
}

###
# login Admin
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "Admin1@example.com",
  "password": "1234admin"
}

###
# Get all users
GET http://localhost:3000/api/users

###
# Delete user
DELETE http://localhost:3000/api/users/6540da38d0eaf07186aa44c0
x-user-id: 6540da38d0eaf07186aa44c0

#
# CARTS
#

###
# create cart
POST http://localhost:3000/api/profile/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQwZDQyNzZlMDljZDlhNjNhM2I1Y2YiLCJlbWFpbCI6InRlc3QxMjMzMjFAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5ODc0OTgxOCwiZXhwIjoxNjk4NzU3MDE4fQ.9jcLUnVRMJqpDZDDvyNTPhIt065T7wuR9UPJrU_Y63k

